import type { RuntimeEventBus } from "@/runtime/core/runtimeEventBus";
import type {
  AgentExecutionContext,
  AgentLoopResult,
  AgentPolicy,
  AgentRunRequest,
  AgentStep,
  PlannerResult,
  ToolCalling
} from "@/runtime/agent/agentContracts";
import { ReflectionEngine } from "@/runtime/agent/reflectionEngine";
import type { ToolName, ToolRequest, ToolResult } from "@/runtime/tool/toolContracts";

export type PatchApprovalCallback = (
  runRequest: AgentRunRequest,
  step: AgentStep,
  patchResult: ToolResult,
  toolRequest: ToolRequest
) => Promise<boolean>;

function createRequestId(prefix: string): string {
  if (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function") {
    return `${prefix}-${crypto.randomUUID()}`;
  }
  return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
}

function firstMeaningfulTerm(value: string): string {
  const match = value.match(/[A-Za-z0-9_./-]+/);
  return match?.[0] ?? "TODO";
}

function getTargetFilePath(context: AgentExecutionContext | undefined): string {
  return (
    context?.primaryFilePath ??
    context?.relatedFilePaths?.[0] ??
    context?.scratchNotePath ??
    "README.md"
  );
}

function buildStructuredPatchProposal(
  request: AgentRunRequest,
  objective: string,
  targetFilePath: string,
  executionContext: AgentExecutionContext | undefined
): string {
  const relatedFiles = executionContext?.relatedFilePaths?.length
    ? executionContext.relatedFilePaths.map((filePath) => `- ${filePath}`).join("\n")
    : "- none";

  const contextSummary = executionContext?.contextSummary ?? "No ranked runtime context available.";
  const excerpt = executionContext?.primaryFileExcerpt?.trim();

  const lines = [
    "# Runtime Change Proposal",
    "",
    "## Request",
    `- Run ID: ${request.runId}`,
    `- Actor ID: ${request.actorId}`,
    `- Mode: ${request.mode}`,
    `- Role: ${request.role}`,
    `- Target File: ${targetFilePath}`,
    `- Objective: ${objective}`,
    "",
    "## Context Summary",
    contextSummary,
    "",
    "## Related Files",
    relatedFiles,
    "",
    "## Proposed Changes",
    `1. Review ${targetFilePath} against the stated objective.`,
    "2. Apply the smallest coherent code or documentation change that satisfies the objective.",
    "3. Re-run the narrowest available validation for the touched slice.",
    "",
    "## Approval Notes",
    "- This file is a structured preview artifact generated by the runtime.",
    "- Approving it should lead to a concrete patch implementation step, not a blind file overwrite."
  ];

  if (excerpt) {
    lines.push(
      "",
      "## Active File Excerpt",
      "```text",
      excerpt,
      "```"
    );
  }

  return lines.join("\n");
}

export class AgentLoop {
  private readonly reflection = new ReflectionEngine();

  constructor(
    private readonly eventBus: RuntimeEventBus,
    private readonly tools: ToolCalling,
    private readonly policy: AgentPolicy,
    private readonly requestPatchApproval?: PatchApprovalCallback
  ) {}

  async run(
    request: AgentRunRequest,
    plan: PlannerResult,
    cancellationSignal: AbortSignal
  ): Promise<AgentLoopResult> {
    const startedAt = Date.now();
    const patchPreviewIds: string[] = [];
    let toolCallsExecuted = 0;
    let stepsExecuted = 0;

    for (const step of plan.steps.slice(0, this.policy.maxSteps)) {
      if (cancellationSignal.aborted) {
        return {
          runId: request.runId,
          status: "cancelled",
          appliedPatchPreviewIds: patchPreviewIds,
          stepsExecuted,
          toolCallsExecuted
        };
      }

      if (Date.now() - startedAt > this.policy.maxRuntimeMs) {
        return {
          runId: request.runId,
          status: "timeout",
          appliedPatchPreviewIds: patchPreviewIds,
          stepsExecuted,
          toolCallsExecuted,
          lastError: "Agent runtime limit exceeded"
        };
      }

      const stepResults: ToolResult[] = [];
      let retries = 0;

      while (retries <= this.policy.maxRetriesPerStep) {
        const iterationResults: ToolResult[] = [];
        for (const toolName of step.expectedTools) {
          if (toolCallsExecuted >= this.policy.maxToolCalls) {
            return {
              runId: request.runId,
              status: "failed",
              appliedPatchPreviewIds: patchPreviewIds,
              stepsExecuted,
              toolCallsExecuted,
              lastError: "Tool call budget reached"
            };
          }

          const toolRequest = this.buildToolRequest(request, step, toolName);
          const result = await this.tools.runTool(toolRequest);
          toolCallsExecuted += 1;
          iterationResults.push(result);

          if (toolName === "apply_patch" && result.status === "ok") {
            const approved = await this.handlePatchApproval(request, step, result, toolRequest);
            if (!approved) {
              return {
                runId: request.runId,
                status: "cancelled",
                appliedPatchPreviewIds: patchPreviewIds,
                stepsExecuted,
                toolCallsExecuted,
                lastError: "Patch preview rejected"
              };
            }

            const previewId =
              typeof result.output === "object" &&
              result.output !== null &&
              "patchId" in result.output
                ? String((result.output as { patchId?: unknown }).patchId ?? "")
                : "";
            if (previewId) {
              patchPreviewIds.push(previewId);
            }
          }
        }

        stepResults.splice(0, stepResults.length, ...iterationResults);
        const reflection = this.reflection.reflect(step, iterationResults);
        if (reflection.done) {
          break;
        }

        retries += 1;
        if (retries > this.policy.maxRetriesPerStep) {
          return {
            runId: request.runId,
            status: "failed",
            appliedPatchPreviewIds: patchPreviewIds,
            stepsExecuted,
            toolCallsExecuted,
            lastError: reflection.issues?.join(" | ")
          };
        }
      }

      stepsExecuted += 1;
      await this.eventBus.emit("agent-runtime", "agent.step.completed", {
        runId: request.runId,
        stepId: step.id,
        stepTitle: step.title,
        toolResults: stepResults
      });
    }

    return {
      runId: request.runId,
      status: "completed",
      appliedPatchPreviewIds: patchPreviewIds,
      stepsExecuted,
      toolCallsExecuted
    };
  }

  private async handlePatchApproval(
    request: AgentRunRequest,
    step: AgentStep,
    result: ToolResult,
    toolRequest: ToolRequest
  ): Promise<boolean> {
    if (!this.policy.requiresApprovalForPatch) {
      return true;
    }

    if (!this.requestPatchApproval) {
      return false;
    }

    return this.requestPatchApproval(request, step, result, toolRequest);
  }

  private buildToolRequest(
    request: AgentRunRequest,
    step: AgentStep,
    toolName: ToolName
  ): ToolRequest {
    const input = this.defaultInputForTool(request, toolName, step.objective);
    return {
      name: toolName,
      requestId: createRequestId("tool"),
      actorId: request.actorId,
      workspaceRoot: request.workspaceRoot,
      input
    };
  }

  private defaultInputForTool(
    request: AgentRunRequest,
    toolName: ToolName,
    objective: string
  ): Record<string, unknown> {
    const executionContext = request.executionContext;
    const targetFilePath = getTargetFilePath(executionContext);

    switch (toolName) {
      case "search_workspace":
        return {
          query: executionContext?.searchQuery ?? objective,
          limit: 50
        };
      case "grep":
        return {
          pattern: firstMeaningfulTerm(executionContext?.searchQuery ?? objective),
          include: executionContext?.primaryFilePath,
          maxResults: 50
        };
      case "run_tests":
        return { commandId: executionContext?.testCommandId ?? "pnpm_test" };
      case "get_git_diff":
        return {
          filePath: executionContext?.gitDiffFilePath ?? executionContext?.primaryFilePath
        };
      case "read_file":
        return { path: targetFilePath };
      case "apply_patch":
        return {
          path: executionContext?.scratchNotePath ?? targetFilePath,
          targetPath: targetFilePath,
          summary: objective,
          proposedContent: buildStructuredPatchProposal(
            request,
            objective,
            targetFilePath,
            executionContext
          ),
          previewOnly: true
        };
      case "list_files":
        return {
          path: executionContext?.primaryFilePath,
          recursive: !executionContext?.primaryFilePath
        };
      case "open_file":
        return { path: targetFilePath };
      case "create_file":
        return {
          path: executionContext?.scratchNotePath ?? "tmp/runtime-agent-note.md",
          content: objective
        };
      case "delete_file":
        return { path: executionContext?.scratchNotePath ?? "tmp/runtime-agent-note.md" };
      case "rename_file":
        return {
          fromPath: executionContext?.scratchNotePath ?? "tmp/runtime-agent-note.md",
          toPath: (executionContext?.scratchNotePath ?? "tmp/runtime-agent-note.md").replace(/\.md$/i, "-renamed.md")
        };
      case "run_terminal_command":
        return {
          command: executionContext?.gitDiffFilePath ? "git diff --stat" : "git status --short",
          cwd: request.workspaceRoot
        };
      case "run_workspace_command":
        return {
          commandId: "git_status"
        };
      case "web_search":
        return {
          query: "typescript release notes",
          purpose: "test web search"
        };
      case "web_fetch":
        return {
          url: "https://www.typescriptlang.org/docs/",
          purpose: "test web fetch"
        };
      case "write_file":
        return {
          path: executionContext?.scratchNotePath ?? "tmp/runtime-agent-note.md",
          content: objective
        };
      default:
        return {};
    }
  }
}
