import type { AppSettings } from "@dbzs/shared";
import { DEFAULT_SETTINGS } from "@dbzs/shared";

export type SettingsCategory =
  | "general"
  | "models"
  | "runtime"
  | "agents_safety"
  | "context_rag"
  | "workspace_editor"
  | "backend"
  | "advanced"
  | "diagnostics";

export type SettingClassification =
  | "user_tunable"
  | "advanced_user_tunable"
  | "secret"
  | "internal_feature_flag"
  | "hard_invariant"
  | "read_only_diagnostic"
  | "orphaned"
  | "deprecated";

export type SettingControl =
  | "toggle"
  | "number"
  | "range"
  | "text"
  | "password"
  | "select"
  | "path"
  | "model_select"
  | "readonly"
  | "percent";

export interface SettingDefinition<T = unknown> {
  key: keyof AppSettings;
  category: SettingsCategory;
  label: string;
  description: string;
  classification: SettingClassification;
  defaultValue: T;
  control: SettingControl;
  validation?: {
    min?: number;
    max?: number;
    step?: number;
    options?: Array<{ value: string; label: string }>;
    maxLength?: number;
  };
  restartRequirement:
    | "none"
    | "next_run"
    | "runtime_restart"
    | "backend_restart"
    | "app_restart";
  sensitive?: boolean;
  experimental?: boolean;
  environmentOverrides?: string[];
  consumerDescription: string;
}

const d = DEFAULT_SETTINGS;

function def<K extends keyof AppSettings>(
  partial: SettingDefinition<AppSettings[K]>,
): SettingDefinition {
  return partial as SettingDefinition;
}

export const SETTINGS_REGISTRY: SettingDefinition[] = [
  def({
    key: "theme",
    category: "general",
    label: "Theme",
    description: "Darstellung der Desktop-Oberfläche.",
    classification: "user_tunable",
    defaultValue: d.theme,
    control: "select",
    validation: {
      options: [
        { value: "dark", label: "Dark" },
        { value: "light", label: "Light" },
      ],
    },
    restartRequirement: "none",
    consumerDescription: "Editor- und Panel-Darstellung",
  }),
  def({
    key: "autoSave",
    category: "general",
    label: "Auto-Save",
    description: "Derzeit ohne Editor-Consumer (orphaned).",
    classification: "orphaned",
    defaultValue: d.autoSave,
    control: "readonly",
    restartRequirement: "none",
    consumerDescription: "Kein aktiver Consumer",
  }),
  def({
    key: "reasoningDisplayMode",
    category: "general",
    label: "Reasoning-Anzeige",
    description: "Wie Reasoning-Traces im Chat dargestellt werden.",
    classification: "user_tunable",
    defaultValue: d.reasoningDisplayMode ?? "summary",
    control: "select",
    validation: {
      options: [
        { value: "hidden", label: "Ausgeblendet" },
        { value: "summary", label: "Zusammenfassung" },
        { value: "expanded", label: "Ausgeklappt" },
      ],
    },
    restartRequirement: "none",
    consumerDescription: "RuntimeChatTab",
  }),
  def({
    key: "editorFontSize",
    category: "workspace_editor",
    label: "Editor-Schriftgröße",
    description: "Schriftgröße im Monaco-Editor.",
    classification: "user_tunable",
    defaultValue: d.editorFontSize,
    control: "range",
    validation: { min: 10, max: 28, step: 1 },
    restartRequirement: "none",
    consumerDescription: "Monaco EditorPane",
  }),
  def({
    key: "terminalShell",
    category: "workspace_editor",
    label: "Terminal-Shell",
    description: "Derzeit nicht verdrahtet — Electron nutzt PowerShell.",
    classification: "orphaned",
    defaultValue: d.terminalShell,
    control: "readonly",
    validation: {
      options: [
        { value: "powershell", label: "PowerShell" },
        { value: "pwsh", label: "pwsh" },
        { value: "cmd", label: "cmd" },
      ],
    },
    restartRequirement: "none",
    consumerDescription: "Kein aktiver Consumer",
  }),
  def({
    key: "safeCommandConfirmation",
    category: "agents_safety",
    label: "Befehl-Bestätigung",
    description: "Bestätigung vor riskanten run_command-Aufrufen.",
    classification: "user_tunable",
    defaultValue: d.safeCommandConfirmation,
    control: "toggle",
    restartRequirement: "next_run",
    consumerDescription: "runtimeChatAgentRunner",
  }),
  def({
    key: "telemetryEnabled",
    category: "advanced",
    label: "Telemetry",
    description: "Fest deaktiviert (Sicherheitsinvariante).",
    classification: "hard_invariant",
    defaultValue: false,
    control: "readonly",
    restartRequirement: "none",
    consumerDescription: "Backend lehnt true ab",
  }),
  def({
    key: "modelsPath",
    category: "models",
    label: "Models-Pfad",
    description: "Verzeichnis lokaler Modelldateien.",
    classification: "user_tunable",
    defaultValue: d.modelsPath,
    control: "path",
    validation: { maxLength: 260 },
    restartRequirement: "backend_restart",
    environmentOverrides: ["DBZS_MODELS_DIR"],
    consumerDescription: "get_models_dir()",
  }),
  def({
    key: "defaultChatModelId",
    category: "models",
    label: "Chat-Modell",
    description: "Primäres Chat-/quality_cpu-Modell.",
    classification: "user_tunable",
    defaultValue: d.defaultChatModelId,
    control: "model_select",
    restartRequirement: "next_run",
    consumerDescription: "modelSelectionBroker",
  }),
  def({
    key: "defaultCoderModelId",
    category: "models",
    label: "Coding-Modell",
    description: "Code-Änderungen und Agent-Implementierung.",
    classification: "user_tunable",
    defaultValue: d.defaultCoderModelId,
    control: "model_select",
    restartRequirement: "next_run",
    consumerDescription: "modelSelectionBroker / runtimeSlotManager",
  }),
  def({
    key: "defaultReviewerModelId",
    category: "models",
    label: "Review-Modell",
    description: "Code-Review und Risikoanalyse.",
    classification: "user_tunable",
    defaultValue: d.defaultReviewerModelId,
    control: "model_select",
    restartRequirement: "next_run",
    consumerDescription: "modelSelectionBroker",
  }),
  def({
    key: "defaultPlannerModelId",
    category: "models",
    label: "Plan-Modell",
    description: "Planung und Architektur.",
    classification: "user_tunable",
    defaultValue: d.defaultPlannerModelId,
    control: "model_select",
    restartRequirement: "next_run",
    consumerDescription: "modelSelectionBroker",
  }),
  def({
    key: "defaultDebugModelId",
    category: "models",
    label: "Debug-Modell",
    description: "Fehleranalyse und Fixes.",
    classification: "user_tunable",
    defaultValue: d.defaultDebugModelId,
    control: "model_select",
    restartRequirement: "next_run",
    consumerDescription: "modelSelectionBroker",
  }),
  def({
    key: "defaultUtilityModelId",
    category: "models",
    label: "Utility-Modell",
    description: "Embedding, Reranking und utility-Slot.",
    classification: "user_tunable",
    defaultValue: d.defaultUtilityModelId ?? "",
    control: "model_select",
    restartRequirement: "runtime_restart",
    consumerDescription: "runtimeSlotManager / utility slot",
  }),
  def({
    key: "defaultVisionModelId",
    category: "models",
    label: "Vision-Modell",
    description: "Basismodell für den vision_gpu-Slot (Bild-/UI-Analyse).",
    classification: "orphaned",
    defaultValue: d.defaultVisionModelId ?? "",
    control: "readonly",
    restartRequirement: "none",
    consumerDescription: "runtimeSlotManager.configuredModelForSlot liest das Feld, aber kein Aufrufer startet vision_gpu (Phase 3: getRecommendedSlot/autoStartSlots)",
  }),
  def({
    key: "defaultOrchestratorModelId",
    category: "models",
    label: "Orchestrator-Modell",
    description: "FunctionGemma / orchestrator_cpu.",
    classification: "user_tunable",
    defaultValue: d.defaultOrchestratorModelId ?? "",
    control: "model_select",
    restartRequirement: "runtime_restart",
    consumerDescription: "backend main + runtimeSlotManager",
  }),
  def({
    key: "modelDiscoveryMode",
    category: "models",
    label: "Modell-Discovery",
    description: "Wie Modelle indexiert und freigegeben werden.",
    classification: "user_tunable",
    defaultValue: d.modelDiscoveryMode ?? "project_local_strict",
    control: "select",
    validation: {
      options: [
        { value: "project_local_strict", label: "Nur Projekt (strict)" },
        { value: "local_with_ollama", label: "Lokal + Ollama" },
        { value: "cloud_enabled", label: "Cloud erlaubt" },
      ],
    },
    restartRequirement: "backend_restart",
    consumerDescription: "backend discovery_mode",
  }),
  def({
    key: "cloudModelsEnabled",
    category: "backend",
    label: "Cloud-Modelle erlauben",
    description: "Cloud-Fallback in Router/Agent Runner.",
    classification: "advanced_user_tunable",
    defaultValue: d.cloudModelsEnabled,
    control: "toggle",
    restartRequirement: "next_run",
    consumerDescription: "modelRouterService / agent_runner",
  }),
  def({
    key: "preferLocalModels",
    category: "models",
    label: "Lokale Modelle bevorzugen",
    description: "Legacy-Router-Pfad (Broker ignoriert).",
    classification: "advanced_user_tunable",
    defaultValue: d.preferLocalModels,
    control: "toggle",
    restartRequirement: "next_run",
    consumerDescription: "modelRouterService (legacy)",
  }),
  def({
    key: "localOnlyModels",
    category: "models",
    label: "Nur lokale Modelle",
    description: "Cloud-Provider sperren.",
    classification: "advanced_user_tunable",
    defaultValue: d.localOnlyModels,
    control: "toggle",
    restartRequirement: "next_run",
    consumerDescription: "agent_runner / legacy router",
  }),
  def({
    key: "localOnly",
    category: "agents_safety",
    label: "Local-Only (Autonomous)",
    description: "Autonomous Session darf nicht in die Cloud.",
    classification: "user_tunable",
    defaultValue: d.localOnly,
    control: "toggle",
    restartRequirement: "next_run",
    consumerDescription: "autonomousSessionService",
  }),
  def({
    key: "ollamaBaseUrl",
    category: "backend",
    label: "Ollama Base URL",
    description: "Derzeit ohne aktiven Registry-Refresh (orphaned).",
    classification: "orphaned",
    defaultValue: d.ollamaBaseUrl,
    control: "readonly",
    validation: { maxLength: 260 },
    restartRequirement: "next_run",
    consumerDescription: "modelProviders (tot)",
  }),
  def({
    key: "openaiApiKey",
    category: "backend",
    label: "OpenAI API Key",
    description:
      "Optionaler Override. Bevorzugt: System-Env OPENAI_API_KEY (Feld leer lassen). Nur ausfüllen, wenn der Key in settings.json liegen soll.",
    classification: "secret",
    defaultValue: d.openaiApiKey,
    control: "password",
    validation: { maxLength: 260 },
    restartRequirement: "next_run",
    sensitive: true,
    environmentOverrides: ["OPENAI_API_KEY"],
    consumerDescription: "cloud_client.py (Settings oder Env)",
  }),
  def({
    key: "anthropicApiKey",
    category: "backend",
    label: "Anthropic API Key",
    description:
      "Optionaler Override. Bevorzugt: System-Env ANTHROPIC_API_KEY (Feld leer lassen). Nur ausfüllen, wenn der Key in settings.json liegen soll.",
    classification: "secret",
    defaultValue: d.anthropicApiKey,
    control: "password",
    validation: { maxLength: 260 },
    restartRequirement: "next_run",
    sensitive: true,
    environmentOverrides: ["ANTHROPIC_API_KEY"],
    consumerDescription: "cloud_client.py (Settings oder Env)",
  }),
  def({
    key: "backendUrl",
    category: "backend",
    label: "Backend URL",
    description: "Basis-URL des lokalen Codee-Backends.",
    classification: "user_tunable",
    defaultValue: d.backendUrl,
    control: "text",
    validation: { maxLength: 260 },
    restartRequirement: "app_restart",
    consumerDescription: "desktop clients",
  }),
  def({
    key: "autoStartChatRuntime",
    category: "runtime",
    label: "Auto-Start Chat Runtime",
    description: "quality_cpu beim Start vorladen.",
    classification: "user_tunable",
    defaultValue: d.autoStartChatRuntime,
    control: "toggle",
    restartRequirement: "app_restart",
    consumerDescription: "runtimeSlotManager.autoStartSlots",
  }),
  def({
    key: "autoStartCodingRuntime",
    category: "runtime",
    label: "Auto-Start Coding Runtime",
    description: "fast_gpu beim Start vorladen.",
    classification: "user_tunable",
    defaultValue: d.autoStartCodingRuntime,
    control: "toggle",
    restartRequirement: "app_restart",
    consumerDescription: "runtimeSlotManager.autoStartSlots",
  }),
  def({
    key: "autoStartVisionRuntime",
    category: "runtime",
    label: "Auto-Start Vision Runtime",
    description: "Derzeit ohne Start-Consumer.",
    classification: "orphaned",
    defaultValue: d.autoStartVisionRuntime ?? false,
    control: "readonly",
    restartRequirement: "none",
    consumerDescription: "Kein aktiver Consumer",
  }),
  def({
    key: "autoStartReviewRuntime",
    category: "runtime",
    label: "Auto-Start Review Runtime",
    description: "Derzeit ohne Start-Consumer.",
    classification: "orphaned",
    defaultValue: d.autoStartReviewRuntime ?? false,
    control: "readonly",
    restartRequirement: "none",
    consumerDescription: "Kein aktiver Consumer",
  }),
  def({
    key: "autoStartOrchestratorRuntime",
    category: "runtime",
    label: "Auto-Start Orchestrator",
    description: "FunctionGemma-Slot beim Backend-Start.",
    classification: "user_tunable",
    defaultValue: d.autoStartOrchestratorRuntime ?? true,
    control: "toggle",
    restartRequirement: "backend_restart",
    consumerDescription: "backend main.py",
  }),
  def({
    key: "idleUnloadWorkModelsMinutes",
    category: "runtime",
    label: "Idle-Unload (Minuten)",
    description: "0 = deaktiviert. Entlädt Arbeitsmodelle nach Idle.",
    classification: "user_tunable",
    defaultValue: d.idleUnloadWorkModelsMinutes ?? 10,
    control: "number",
    validation: { min: 0, max: 240, step: 1 },
    restartRequirement: "none",
    consumerDescription: "lazyRuntimePolicy",
  }),
  def({
    key: "stopDesktopRuntimesOnExit",
    category: "runtime",
    label: "Runtimes beim Beenden stoppen",
    description: "Desktop-Prozesse beim App-Exit beenden.",
    classification: "user_tunable",
    defaultValue: d.stopDesktopRuntimesOnExit,
    control: "toggle",
    restartRequirement: "none",
    consumerDescription: "electron before-quit",
  }),
  def({
    key: "chatRuntimeSlot",
    category: "runtime",
    label: "Chat Slot",
    description: "Fest: quality_cpu (Slot-Contract).",
    classification: "hard_invariant",
    defaultValue: "quality_cpu",
    control: "readonly",
    restartRequirement: "none",
    consumerDescription: "runtime-slots.json",
  }),
  def({
    key: "codingRuntimeSlot",
    category: "runtime",
    label: "Coding Slot",
    description: "Fest: fast_gpu (Slot-Contract).",
    classification: "hard_invariant",
    defaultValue: "fast_gpu",
    control: "readonly",
    restartRequirement: "none",
    consumerDescription: "runtime-slots.json",
  }),
  def({
    key: "orchestratorRuntimeSlot",
    category: "runtime",
    label: "Orchestrator Slot",
    description: "Fest: orchestrator_cpu.",
    classification: "hard_invariant",
    defaultValue: "orchestrator_cpu",
    control: "readonly",
    restartRequirement: "none",
    consumerDescription: "runtime-slots.json",
  }),
  def({
    key: "chatRuntimePort",
    category: "runtime",
    label: "Chat Port",
    description: "Effektiver Port aus Slot-Contract (8081).",
    classification: "read_only_diagnostic",
    defaultValue: d.chatRuntimePort,
    control: "readonly",
    restartRequirement: "none",
    consumerDescription: "runtime-slots.json",
  }),
  def({
    key: "codingRuntimePort",
    category: "runtime",
    label: "Coding Port",
    description: "Effektiver Port aus Slot-Contract (8082).",
    classification: "read_only_diagnostic",
    defaultValue: d.codingRuntimePort,
    control: "readonly",
    restartRequirement: "none",
    consumerDescription: "runtime-slots.json",
  }),
  def({
    key: "orchestratorRuntimePort",
    category: "runtime",
    label: "Orchestrator Port",
    description: "Effektiver Port aus Slot-Contract (8084).",
    classification: "read_only_diagnostic",
    defaultValue: d.orchestratorRuntimePort ?? 8084,
    control: "readonly",
    restartRequirement: "none",
    consumerDescription: "runtime-slots.json",
  }),
  def({
    key: "timeoutStreamIdleSeconds",
    category: "runtime",
    label: "Stream-Idle Timeout (s)",
    description: "Max. Pause ohne neues Token während der Generierung.",
    classification: "advanced_user_tunable",
    defaultValue: d.timeoutStreamIdleSeconds ?? 30,
    control: "number",
    validation: { min: 5, max: 3600 },
    restartRequirement: "next_run",
    consumerDescription: "timeoutConfig / runtimeChatStore",
  }),
  def({
    key: "timeoutFirstTokenSeconds",
    category: "runtime",
    label: "First-Token Timeout (s)",
    description: "Wartezeit bis zum ersten Modell-Token nach HTTP-Send.",
    classification: "advanced_user_tunable",
    defaultValue: d.timeoutFirstTokenSeconds ?? 90,
    control: "number",
    validation: { min: 10, max: 3600 },
    restartRequirement: "next_run",
    consumerDescription: "timeoutConfig / runtimeChatStore",
  }),
  def({
    key: "timeoutGenerationSeconds",
    category: "runtime",
    label: "Generation Timeout (s)",
    description: "Absolute Obergrenze für eine laufende Generierung.",
    classification: "advanced_user_tunable",
    defaultValue: d.timeoutGenerationSeconds ?? 300,
    control: "number",
    validation: { min: 30, max: 14400 },
    restartRequirement: "next_run",
    consumerDescription: "timeoutConfig / runtimeChatStore",
  }),
  def({
    key: "timeoutPromptEvalSeconds",
    category: "runtime",
    label: "Prompt-Eval Timeout (s)",
    description: "Timeout für Prompt-Auswertung vor dem ersten Token.",
    classification: "advanced_user_tunable",
    defaultValue: d.timeoutPromptEvalSeconds ?? 90,
    control: "number",
    validation: { min: 10, max: 3600 },
    restartRequirement: "next_run",
    consumerDescription: "timeoutConfig / runtimeChatStore",
  }),
  def({
    key: "timeoutCpuSafeStreamIdleSeconds",
    category: "runtime",
    label: "CPU-Safe Stream-Idle (s)",
    description: "Stream-Idle bei cpu_safe / gpuLayers=0 (langsamere CPU-Inferenz).",
    classification: "advanced_user_tunable",
    defaultValue: d.timeoutCpuSafeStreamIdleSeconds ?? 180,
    control: "number",
    validation: { min: 15, max: 3600 },
    restartRequirement: "next_run",
    consumerDescription: "timeoutConfig / runtimeChatStore (cpu path)",
  }),
  def({
    key: "timeoutCpuSafeFirstTokenSeconds",
    category: "runtime",
    label: "CPU-Safe First-Token (s)",
    description: "First-Token-Budget bei cpu_safe / gpuLayers=0.",
    classification: "advanced_user_tunable",
    defaultValue: d.timeoutCpuSafeFirstTokenSeconds ?? 120,
    control: "number",
    validation: { min: 15, max: 3600 },
    restartRequirement: "next_run",
    consumerDescription: "timeoutConfig / runtimeChatStore (cpu path)",
  }),
  def({
    key: "timeoutCpuSafeGenerationSeconds",
    category: "runtime",
    label: "CPU-Safe Generation (s)",
    description: "Generierungs-Obergrenze bei cpu_safe / gpuLayers=0.",
    classification: "advanced_user_tunable",
    defaultValue: d.timeoutCpuSafeGenerationSeconds ?? 600,
    control: "number",
    validation: { min: 60, max: 14400 },
    restartRequirement: "next_run",
    consumerDescription: "timeoutConfig / runtimeChatStore (cpu path)",
  }),
  def({
    key: "agentExecutionEnabled",
    category: "agents_safety",
    label: "Agent-Ausführung aktiv",
    description: "Derzeit ohne Gate-Consumer (orphaned).",
    classification: "orphaned",
    defaultValue: d.agentExecutionEnabled,
    control: "readonly",
    restartRequirement: "none",
    consumerDescription: "Kein aktiver Consumer",
  }),
  def({
    key: "safeMode",
    category: "agents_safety",
    label: "Safe Mode",
    description: "Strenge Sicherheitsgates / Cloud-Sperre.",
    classification: "user_tunable",
    defaultValue: d.safeMode,
    control: "toggle",
    restartRequirement: "next_run",
    consumerDescription: "autonomousSession / agent_runner",
  }),
  def({
    key: "maxAgentRuntimeSeconds",
    category: "agents_safety",
    label: "Max Agent Runtime (s)",
    description: "Obergrenze für Agent-/Command-Timeouts.",
    classification: "user_tunable",
    defaultValue: d.maxAgentRuntimeSeconds,
    control: "number",
    validation: { min: 30, max: 86400 },
    restartRequirement: "next_run",
    consumerDescription: "autonomousSession / electron",
  }),
  def({
    key: "maxAutonomousSteps",
    category: "agents_safety",
    label: "Max Autonomous Steps",
    description: "Schritt autonomer Schritte pro Session.",
    classification: "user_tunable",
    defaultValue: d.maxAutonomousSteps,
    control: "number",
    validation: { min: 1, max: 200 },
    restartRequirement: "next_run",
    consumerDescription: "autonomousSessionService",
  }),
  def({
    key: "maxDebugRetries",
    category: "agents_safety",
    label: "Max Debug Retries",
    description: "Wiederholungen bei Debug-Fehlschlägen.",
    classification: "user_tunable",
    defaultValue: d.maxDebugRetries,
    control: "number",
    validation: { min: 0, max: 20 },
    restartRequirement: "next_run",
    consumerDescription: "autonomousSessionService",
  }),
  def({
    key: "maxFailedTaskRetries",
    category: "agents_safety",
    label: "Max Failed Task Retries",
    description: "Wiederholungen fehlgeschlagener Tasks.",
    classification: "user_tunable",
    defaultValue: d.maxFailedTaskRetries,
    control: "number",
    validation: { min: 0, max: 10 },
    restartRequirement: "next_run",
    consumerDescription: "autonomousSessionService",
  }),
  def({
    key: "maxFileScanCount",
    category: "workspace_editor",
    label: "Max File Scan Count",
    description: "Obergrenze für Workspace-Dateiscan.",
    classification: "user_tunable",
    defaultValue: d.maxFileScanCount,
    control: "number",
    validation: { min: 100, max: 100000 },
    restartRequirement: "next_run",
    consumerDescription: "workspaceService / electron",
  }),
  def({
    key: "contextSpoolerEnabled",
    category: "context_rag",
    label: "Context Spooler",
    description: "Lane-basiertes Kontext-Packing.",
    classification: "advanced_user_tunable",
    defaultValue: d.contextSpoolerEnabled ?? true,
    control: "toggle",
    restartRequirement: "next_run",
    consumerDescription: "runtimeChatStore",
  }),
  def({
    key: "ragEnabled",
    category: "context_rag",
    label: "RAG aktiv",
    description: "Retrieval-Augmented Generation im Chat.",
    classification: "user_tunable",
    defaultValue: d.ragEnabled ?? true,
    control: "toggle",
    restartRequirement: "next_run",
    consumerDescription: "runtimeChatStore",
  }),
  def({
    key: "hybridRetrievalEnabled",
    category: "context_rag",
    label: "Hybrid Retrieval",
    description: "Kombiniert lexikalische und semantische Suche.",
    classification: "advanced_user_tunable",
    defaultValue: d.hybridRetrievalEnabled ?? true,
    control: "toggle",
    restartRequirement: "next_run",
    consumerDescription: "runtimeChatStore",
  }),
  def({
    key: "reasoningTraceEnabled",
    category: "context_rag",
    label: "Reasoning Trace speichern",
    description: "Persistiert Reasoning-Traces.",
    classification: "advanced_user_tunable",
    defaultValue: d.reasoningTraceEnabled ?? true,
    control: "toggle",
    restartRequirement: "next_run",
    consumerDescription: "runtimeChatStore",
  }),
  def({
    key: "tokenBudgetOutputReserveRatio",
    category: "context_rag",
    label: "Output-Reserve (%)",
    description: "Anteil des Kontextfensters für Output (intern 0–1).",
    classification: "advanced_user_tunable",
    defaultValue: d.tokenBudgetOutputReserveRatio ?? 0.22,
    control: "percent",
    validation: { min: 0, max: 0.8, step: 0.01 },
    restartRequirement: "next_run",
    consumerDescription: "runtimeChatStore / contextSpooler",
  }),
  def({
    key: "tokenBudgetToolReserveRatio",
    category: "context_rag",
    label: "Tool-Reserve (%)",
    description: "Anteil für Tool-Payloads.",
    classification: "advanced_user_tunable",
    defaultValue: d.tokenBudgetToolReserveRatio ?? 0.07,
    control: "percent",
    validation: { min: 0, max: 0.5, step: 0.01 },
    restartRequirement: "next_run",
    consumerDescription: "runtimeChatStore",
  }),
  def({
    key: "tokenBudgetSafetyReserveRatio",
    category: "context_rag",
    label: "Safety-Reserve (%)",
    description: "Sicherheitsreserve im Token-Budget.",
    classification: "advanced_user_tunable",
    defaultValue: d.tokenBudgetSafetyReserveRatio ?? 0.05,
    control: "percent",
    validation: { min: 0, max: 0.5, step: 0.01 },
    restartRequirement: "next_run",
    consumerDescription: "runtimeChatStore",
  }),
  def({
    key: "runtimeChatUseBroker",
    category: "advanced",
    label: "Broker-Routing",
    description: "Broker ist immer aktiv — Schalter ohne Wirkung.",
    classification: "orphaned",
    defaultValue: d.runtimeChatUseBroker ?? true,
    control: "readonly",
    restartRequirement: "none",
    consumerDescription: "Kein Lesepfad",
  }),
  def({
    key: "runtimeChatEnableSlotValidation",
    category: "advanced",
    label: "Slot-Validation",
    description: "Erzwingt Slot-Contract-Prüfung.",
    classification: "advanced_user_tunable",
    defaultValue: d.runtimeChatEnableSlotValidation ?? true,
    control: "toggle",
    restartRequirement: "next_run",
    experimental: true,
    consumerDescription: "runtimeChatStore",
  }),
  def({
    key: "runtimeChatEnableAgentTurnLoop",
    category: "advanced",
    label: "Agent Turn-Loop",
    description: "Mehrstufige Agent-Turns im Runtime Chat.",
    classification: "advanced_user_tunable",
    defaultValue: d.runtimeChatEnableAgentTurnLoop ?? true,
    control: "toggle",
    restartRequirement: "next_run",
    experimental: true,
    consumerDescription: "runtimeChatStore",
  }),
  def({
    key: "runtimeChatEnableStrictFallback",
    category: "advanced",
    label: "Strict Fallback",
    description: "Strenge Fallback-Policy bei Routing-Fehlern.",
    classification: "advanced_user_tunable",
    defaultValue: d.runtimeChatEnableStrictFallback ?? true,
    control: "toggle",
    restartRequirement: "next_run",
    experimental: true,
    consumerDescription: "runtimeChatStore",
  }),
  def({
    key: "runtimeChatEnableDiagnostics",
    category: "advanced",
    label: "Diagnostics speichern",
    description: "Broker-Entscheidungen persistieren.",
    classification: "advanced_user_tunable",
    defaultValue: d.runtimeChatEnableDiagnostics ?? true,
    control: "toggle",
    restartRequirement: "next_run",
    experimental: true,
    consumerDescription: "runtimeChatStore",
  }),
  def({
    key: "runtimeChatShadowMode",
    category: "advanced",
    label: "Shadow Mode",
    description: "Vergleicht Broker vs. Legacy-Router.",
    classification: "advanced_user_tunable",
    defaultValue: d.runtimeChatShadowMode ?? false,
    control: "toggle",
    restartRequirement: "next_run",
    experimental: true,
    consumerDescription: "runtimeChatStore",
  }),
  def({
    key: "runtimeChatStopOnShadowMismatch",
    category: "advanced",
    label: "Stop bei Shadow-Mismatch",
    description: "Zusätzlich Env VITE_DBZS_ENFORCE_SHADOW_MISMATCH_STOP.",
    classification: "advanced_user_tunable",
    defaultValue: d.runtimeChatStopOnShadowMismatch ?? false,
    control: "toggle",
    restartRequirement: "next_run",
    experimental: true,
    environmentOverrides: ["VITE_DBZS_ENFORCE_SHADOW_MISMATCH_STOP"],
    consumerDescription: "runtimeChatStore",
  }),
  def({
    key: "runtimeChatCanaryPercent",
    category: "advanced",
    label: "Canary Anteil (%)",
    description: "Derzeit nur Labeling — kein Routing-Gate.",
    classification: "advanced_user_tunable",
    defaultValue: d.runtimeChatCanaryPercent ?? 100,
    control: "number",
    validation: { min: 0, max: 100 },
    restartRequirement: "next_run",
    experimental: true,
    consumerDescription: "runtimeChatStore (labels)",
  }),
  def({
    key: "conversationControlV2",
    category: "advanced",
    label: "Conversation Control V2",
    description: "Internes Feature-Flag für Turn-Kontrolle.",
    classification: "internal_feature_flag",
    defaultValue: d.conversationControlV2 ?? true,
    control: "toggle",
    restartRequirement: "next_run",
    experimental: true,
    consumerDescription: "runtimeChatStore",
  }),
  def({
    key: "legacyStructuredMarkupParser",
    category: "advanced",
    label: "Legacy Markup Parser",
    description: "Veraltet — kein Consumer.",
    classification: "deprecated",
    defaultValue: d.legacyStructuredMarkupParser ?? false,
    control: "readonly",
    restartRequirement: "none",
    consumerDescription: "Kein Consumer",
  }),
];

export const SETTINGS_TABS: Array<{ id: SettingsCategory; label: string }> = [
  { id: "general", label: "Allgemein" },
  { id: "models", label: "Modelle" },
  { id: "runtime", label: "Runtime" },
  { id: "agents_safety", label: "Agenten & Sicherheit" },
  { id: "context_rag", label: "Kontext & RAG" },
  { id: "workspace_editor", label: "Workspace & Editor" },
  { id: "backend", label: "Backend" },
  { id: "advanced", label: "Erweitert" },
  { id: "diagnostics", label: "Diagnose" },
];

export function getSettingDefinition(key: keyof AppSettings): SettingDefinition | undefined {
  return SETTINGS_REGISTRY.find((entry) => entry.key === key);
}

export function settingsByCategory(category: SettingsCategory): SettingDefinition[] {
  return SETTINGS_REGISTRY.filter((entry) => entry.category === category);
}

export function userTunableSettings(): SettingDefinition[] {
  return SETTINGS_REGISTRY.filter((entry) =>
    ["user_tunable", "advanced_user_tunable", "secret"].includes(entry.classification),
  );
}

export function isEditableClassification(classification: SettingClassification): boolean {
  return (
    classification === "user_tunable" ||
    classification === "advanced_user_tunable" ||
    classification === "secret" ||
    classification === "internal_feature_flag"
  );
}
